### ISSUE TITLE
Error in running trainer.py

### ISSUE THREAD

**Issue by meetmustafa** [perseus784/BvS#1]
trainer.py
2 ['superman', 'batman']
rawdata/superman
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /io/opencv/modules/imgproc/src/resize.cpp, line 4044
Traceback (most recent call last):
  File "/home/mustafa/Downloads/BvS-master/trainer.py", line 3, in <module>
    from utils import utils
  File "/home/mustafa/Downloads/BvS-master/utils.py", line 3, in <module>
    from config import *
  File "/home/mustafa/Downloads/BvS-master/config.py", line 10, in <module>
    ppr.image_processing(raw_data,data_path,height,width)
  File "/home/mustafa/Downloads/BvS-master/preprocessing.py", line 16, in image_processing
    im=cv2.resize(im,(height,width))
cv2.error: OpenCV(3.4.1) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

**Comment by perseus784** [comment]
It seems like an OpenCV error. This is probably due to **no images in the required folders**. Try to put those images in the required folders as given in the instructions. Also please check where you extracted these images if it is taken from the repo, it should be extracted in _BvS-master_ folder itself, not in _rawdata_. 
If you are going to use your own images then put it in respective folders _with their own names_ inside _rawdata_ folder

**Comment by meetmustafa** [comment]
As you said i am now using my own images and putting them in _rawdata_ folder with their own names but still getting the same error
```
2 ['Bill Gates', 'Elon Musk']
rawdata/Bill Gates
OpenCV(3.4.1) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /io/opencv/modules/imgproc/src/resize.cpp, line 4044
Traceback (most recent call last):
  File "/home/mustafa/Downloads/BvS-master/trainer.py", line 3, in <module>
    from utils import utils
  File "/home/mustafa/Downloads/BvS-master/utils.py", line 3, in <module>
    from config import *
  File "/home/mustafa/Downloads/BvS-master/config.py", line 10, in <module>
    ppr.image_processing(raw_data,data_path,height,width)
  File "/home/mustafa/Downloads/BvS-master/preprocessing.py", line 16, in image_processing
    im=cv2.resize(im,(height,width))
cv2.error: OpenCV(3.4.1) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize
```

**Comment by meetmustafa** [comment]
Found it. It was with the path of image Thanks for your response
